version: '3'

services:
  clickhouse:
    image: yandex/clickhouse-server:20.5.3
    volumes:
      - ./.docker/users.xml:/etc/clickhouse-server/users.xml
    ports:
      - 8123:8123
      - 9000:9000
